### ISSUE TITLE
withUserPosition not working on Android

### ISSUE THREAD

**Issue by NathanBrodin** [liodali/osm_flutter#507]
Hi, I am not enable to make withUserPosition working on Android.
My simple goal is to make the map follow the user, and to get his position when it changes.
- On IOS, the map moves, and the `handleLocationChanged` returns the correct position.
- On Android, the map doesn't moves, and the `handleLocationChanged` is not triggered.

My flutter_osm_plugin version is `1.0.0-rc`, as you recommanded it in other issues. I tried with newer version but they don't work.
I am using `ext.kotlin_version = '1.9.22'` (latest), `compileSdkVersion 34`.

To try to understand, I made a simple Flutter app:
```dart
class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  GeoPoint? currentPosition;
  bool isMapReady = false;

  // init the position using the user location
  final controller = MapController.withUserPosition(
    trackUserLocation: const UserTrackingOption(
      enableTracking: true,
      unFollowUser: false,
    ),
  );

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  void handleMapIsReady(bool isReady) async {
    setState(() {
      isMapReady = isReady;
    });
  }

  void handleLocationChanged(GeoPoint point) {
    if (isMapReady) {
      setState(() {
        currentPosition = point;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Flutter OSM Plugin"),
      ),
      body: SizedBox(
        child: Column(
          children: [
            ListTile(
              title: const Text("Current location:"),
              subtitle: Text(
                  "lat: ${currentPosition?.latitude} | lon: ${currentPosition?.longitude}"),
            ),
            Expanded(
              child: OSMFlutter(
                controller: controller,
                onMapIsReady: handleMapIsReady,
                osmOption: OSMOption(
                  userTrackingOption: const UserTrackingOption(
                    enableTracking: true,
                    unFollowUser: false,
                  ),
                  zoomOption: const ZoomOption(
                    initZoom: 17,
                    minZoomLevel: 3,
                    maxZoomLevel: 19,
                    stepZoom: 1.0,
                  ),
                  userLocationMarker: UserLocationMaker(
                    personMarker: const MarkerIcon(
                      icon: Icon(
                        Icons.location_history_rounded,
                        color: Colors.red,
                        size: 48,
                      ),
                    ),
                    directionArrowMarker: const MarkerIcon(
                      icon: Icon(
                        Icons.double_arrow,
                        size: 48,
                      ),
                    ),
                  ),
                ),
                mapIsLoading: const Center(
                  child: Column(
                    children: [
                      CircularProgressIndicator(),
                      Text("Loading the map, please wait..."),
                    ],
                  ),
                ),
                onLocationChanged: handleLocationChanged,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

This example should follow the user, display his location, and update it everytime it changes. It does not do any of that on Android, but does on IOS.

Reading the docs, I don't see what I am missing. I tried with 1.0.0-rc.1, and 1.0.0-rc.2 has dependencies problems.

**Comment by liodali** [comment]
I will check it why 
but for `1.0.0-rc.2`it require latest flutter version `3.19`because we migrate from `dart:html` to the web package since they will remove it in upcoming versions
but i will check that and return to you with solution

**Comment by tmp78** [comment]
I have a similar problem on Android. I'm starting without tracking the user. Then I use the same code (after clicking a button) as in the sample application (only using the provider):
```
  void switchTracking(BuildContext context) async {
    if (!_trackUser) {
      ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Long press to show route')));
      _trackUser = true;
      notifyListeners();
      await _controller?.currentLocation();
      await _controller?.enableTracking(
        enableStopFollow: true,
        disableUserMarkerRotation: true,
        anchor: Anchor.left,
      );
    } else {
      await _controller?.enableTracking(
        enableStopFollow: false,
        disableUserMarkerRotation: true,
        anchor: Anchor.left,
      );
      // if (_userLocation != null) {
      //   await _controller?.goToLocation(_userLocation!);
      // }
    }
    //await _controller?.setZoom(zoomLevel: 18);
  }
```
The above code works for user tracking on iOS, it does not work on Android (after clicking the button, the map centers on the user's location, then the map moves once, along with the marker, which does not stay in the center, then nothing else happens). I checked that onLocationChanged works well. The sample app has the same problem in Android. I'm using Flutter 3.19.3 (3.16.9 before, with the same result) and flutter_osm_plugin 0.70.4.

**Comment by liodali** [comment]
just small remark that if you move the map when even enable tracking is true the map will stop follow automatically 
the same behavior as google map and some request from older developer which cause that map will become unusable 
so we stopfollow automatically when use start move the map 
to return follow user  just re-call again
```dart
await _controller?.currentLocation();
await _controller?.enableTracking(
        enableStopFollow: true,
        disableUserMarkerRotation: true,
        anchor: Anchor.left,
      );
```

**Comment by tmp78** [comment]
The above code is from your example app. But you suggesting, that it should be something like that:
```dart
void switchTracking(BuildContext context) async {
    if (!_trackUser) {
      ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Long press to show route')));
      _trackUser = true;
      notifyListeners();
    }
    await _controller?.currentLocation();
    await _controller?.enableTracking(
      enableStopFollow: true,
      disableUserMarkerRotation: true,
      anchor: Anchor.left,
    );
  }
```
? Then, after manually moving the map with tracking turned on and clicking the button again, tracking does not start again. It was OK in the previous version (on iOS, of course). On Android it looks like this:

![android](https://github.com/liodali/osm_flutter/assets/97254628/cf7ee3d3-93e0-4503-8112-793663a2ddb3)

Works only, if you click button. Then immediately stops tracking the user. After anther button click jumps to user position and so on...

On iOS it looks OK (except the icon doesn't always change to gps_fixed):

![ios](https://github.com/liodali/osm_flutter/assets/97254628/6353b32d-ae2a-4697-97e0-093aaa8dcb42)

**Comment by liodali** [comment]
I apologie I suggest the way 
when tracking is active you just need to use this code :
```dart
 await controller.enableTracking(
                enableStopFollow: false,
                disableUserMarkerRotation: true,
                anchor: Anchor.left,
              );
```
and also I will do publish fix this night concerning this issue

**Comment by tmp78** [comment]
Thanks for your support. Will the fix also be implemented in the stable version branch? Like the creator of this thread, I also have a problem with installing version 1.0.0-rc.2. In my case it has dependencies problems with the just_audio_background package.

**Comment by liodali** [comment]
can you share the issue with the dependencies ?

**Comment by tmp78** [comment]
Sure.
```
Because no versions of just_audio_background match >0.0.1-beta.11 <0.1.0 and just_audio_background 0.0.1-beta.11 depends on audio_service ^0.18.9, just_audio_background ^0.0.1-beta.11 requires audio_service ^0.18.9.
And because audio_service >=0.17.0-nullsafety.0 depends on js ^0.6.3, just_audio_background ^0.0.1-beta.11 requires js ^0.6.3.
And because flutter_osm_plugin >=1.0.0-rc.2 depends on flutter_osm_web >=1.0.0-rc.2 <1.0.1 which depends on js ^0.7.1, just_audio_background ^0.0.1-beta.11 is incompatible with flutter_osm_plugin >=1.0.0-rc.2.
So, because kutno depends on both just_audio_background ^0.0.1-beta.11 and flutter_osm_plugin ^1.0.0-rc.2, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on flutter_osm_plugin: flutter pub add flutter_osm_plugin:^0.70.4
```

**Comment by liodali** [comment]
did you try to override dependencies : js to this version  `^0.7.1`

**Comment by tmp78** [comment]
Ok, after overriding dependencies and updating kotlin version to 1.9.23, I could use the version 1.0.0-rc.2. At first glance, it looks like just_audio_background works fine with js 0.7.1.

**Comment by liodali** [comment]
the new version `1.0.0-rc.3` is published

**Comment by tmp78** [comment]
On Android it works for me just like before. I can't run it on iOS right now:
```
Swift Compiler Error (Xcode): Cannot find type 'RectShapeOSM' in scope
/Users/del/.pub-cache/hosted/pub.dev/flutter_osm_plugin-1.0.0-rc.3/ios/Classes/Extension.swift:520:10

Swift Compiler Error (Xcode): Cannot find type 'CircleOSM' in scope
/Users/del/.pub-cache/hosted/pub.dev/flutter_osm_plugin-1.0.0-rc.3/ios/Classes/Extension.swift:537:10

Swift Compiler Error (Xcode): Cannot find type 'ShapeTypes' in scope
/Users/del/.pub-cache/hosted/pub.dev/flutter_osm_plugin-1.0.0-rc.3/ios/Classes/map_view/osm_map.swift:540:73

Swift Compiler Error (Xcode): No type named 'LocationPermission' in module 'OSMFlutterFramework'
/Users/del/.pub-cache/hosted/pub.dev/flutter_osm_plugin-1.0.0-rc.3/ios/Classes/map_view/osm_map.swift:607:53

Swift Compiler Error (Xcode): Cannot find type 'MapMarkerHandler' in scope
/Users/del/.pub-cache/hosted/pub.dev/flutter_osm_plugin-1.0.0-rc.3/ios/Classes/map_view/osm_map.swift:12:103

Swift Compiler Error (Xcode): Cannot find type 'OSMUserLocationHandler' in scope
/Users/del/.pub-cache/hosted/pub.dev/flutter_osm_plugin-1.0.0-rc.3/ios/Classes/map_view/osm_map.swift:12:120
```

This is just a fragment. flutter clean doesn't help.

**Comment by liodali** [comment]
oh really i will check it

**Comment by tmp78** [comment]
```
[!] CocoaPods could not find compatible versions for pod "flutter_osm_plugin":
  In Podfile:
    flutter_osm_plugin (from `.symlinks/plugins/flutter_osm_plugin/ios`)

Specs satisfying the `flutter_osm_plugin (from `.symlinks/plugins/flutter_osm_plugin/ios`)` dependency were found, but they required a higher minimum deployment target.
```
What minimum ios version is currently required? I'm using iOS 12.

**Comment by liodali** [comment]
minimum version 13.0

**Comment by tmp78** [comment]
Now on iOS device the map moves faster then the user marker:-) So after a while the marker is not visible on the map. Thank you for your support, but I think I give up a user tracking.

**Comment by liodali** [comment]
can you share a video we can fix that
we should not give up

**Comment by liodali** [comment]
I will fix some API in iOS sdk I will try to do publish this night at maximum tomorrow will be ready 
hope this fix will solve the issue

**Comment by tmp78** [comment]
As i wrote, after a while, marker is not visible. Video:
![screen](https://github.com/liodali/osm_flutter/assets/97254628/a04820d2-37cc-447e-9c71-218c63ebfe83)

**Comment by liodali** [comment]
I will publish fix for this in couples of hours sorry for being late

**Comment by liodali** [comment]
I'm sorry for being late, I tried yesterday to fix all issues related to iOS side, today I success to almost fix them all.
I will try to do publish today night or tomorrow sorry again my apologies

**Comment by liodali** [comment]
the new version is available now `1.0.0-rc.4`

**Comment by liodali** [comment]
the new version is ready `1.0.0-rc.4`

**Comment by liodali** [comment]
on android you're testing on emulator or reald device ?

**Comment by NathanBrodin** [comment]
> @tmp78 the new version is ready `1.0.0-rc.4`

Hi, when updating my project to the new version, I always get dependencies errors. Even if I try changing other packages versions, `flutter_osm_plugin` will always be the problem, and it will have conflicts with other packages.

Here's the output I get when trying `flutter_osm_plugin: ^1.0.0-rc.4`:

```bash
flutter pub get

Resolving dependencies... (1.7s)
Note: test_api is pinned to version 0.6.1 by integration_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because every version of integration_test from sdk depends on test_api 0.6.1 and test >=1.25.0 depends on test_api 0.7.0, integration_test from sdk is incompatible with test
  >=1.25.0.
And because test >=1.21.5 <1.25.1 depends on js ^0.6.4 and flutter_osm_web >=1.0.0-rc.2 depends on js ^0.7.1, one of integration_test from sdk or test >=1.21.5 or flutter_osm_web
  >=1.0.0-rc.2 must be false.
And because bmoveon depends on flutter_osm_plugin ^1.0.0-rc.4 which depends on flutter_osm_web >=1.0.0-rc.3 <1.0.1, integration_test from sdk is incompatible with test >=1.21.5.
So, because bmoveon depends on both integration_test from sdk and test ^1.24.3, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on flutter_osm_plugin: flutter pub add flutter_osm_plugin:^1.0.0-rc.1
```

**Comment by tmp78** [comment]
Try to override dependencies in pubspec.yaml:
```
dependency_overrides:
  js: '0.7.1'
```
@liodali, I'm testing on simulator. But I'll try on a physical device. I need to go for a walk:-)

**Comment by liodali** [comment]
try to override js dependency to 0.7.1

**Comment by tmp78** [comment]
@liodali, I tested the latest version on a physical device running Android 11 and on a simulator with Android 12.  It works as I described in this post: [https://github.com/liodali/osm_flutter/issues/507#issuecomment-1986675627](url)
Works only, if I click a button. Then immediately stops tracking the user. After another button click jumps to user position and so on...
But there is a small change. I had to change the order of the code:
```dart
      await _controller?.enableTracking(
        enableStopFollow: true,
        disableUserMarkerRotation: false,
        anchor: Anchor.left,
      );
      await _controller?.currentLocation();
```
In previous version the line with controller?.currentLocation() was before controller?.enableTracking() and that worked, but stopped in current version. I mean it stopped jumping to the user's position because the tracking didn't work then and now.
I have a question for you.  Have you tested this on any Android device? Does this work for you? If so, on what Android versions? Maybe there is a problem with the Android version? Or maybe some permissions problem?

**Comment by NathanBrodin** [comment]
Hi again,

I did some testing on `flutter_osm_plugin: ^1.0.0-rc.4` and here's what I found:

- **On iOS,** the map follows the user, and the `onLocationChanged` method is also triggered with the correct coordinates.
- **On the Android emulator**, the map **does not** follow the user, but the `onLocationChanged` method is triggered with the correct coordinates.
- **On a real Android device**, it acts the same as on an emulator.

So I still have the same issues with Android as mentioned at the beginning of this GitHub issue.

**Comment by liodali** [comment]
you are right its not working in android i will work on that tomorrow i will publish fix for it by this weekend

**Comment by liodali** [comment]
I fixed the issue i will publish new version tomight

**Comment by NathanBrodin** [comment]
Ok great, looking forward to test it !

**Comment by liodali** [comment]
The new version is ready `1.0.0-rc.5`

**Comment by NathanBrodin** [comment]
Hi, **I can confirm `1.0.0-rc.5` is working 🎉 !!!**
Thanks for your work!

I'm closing the issue now. (And you might want to close the other 120 issues opened because they do not look good on the repo.)

**Comment by tmp78** [comment]
@liodali, Thanks for your support.
I can confirm that tracking works on iOS and Android simulators.

This is enough for my needs, but I see a few more problems. For example, the way the user marker and the map are moved. First the marker moves, then the map centers. This causes, for example, at higher speeds, that the user's marker comes very close to the edge of the screen. This happens, for example, on the Android simulator with a simulated user speed of x5. In my opinion, the marker should be stationary and only the map should move.
In my other issue I described that an icon defined in directionArrowMarker seems to have no effect on iOS.  This problem still exists - On iOS, the icon defined in the personMarker property is displayed, while on Android, the icon defined in the directionArrowMarker property is displayed.
Thank you again!

**Comment by tmp78** [comment]
Oh my, there is a serious bug that wasn't there before. I'll create a new issue soon.

**Comment by liodali** [comment]
> @liodali, Thanks for your support. I can confirm that tracking works on iOS and Android simulators.
> 
> This is enough for my needs, but I see a few more problems. For example, the way the user marker and the map are moved. First the marker moves, then the map centers. This causes, for example, at higher speeds, that the user's marker comes very close to the edge of the screen. This happens, for example, on the Android simulator with a simulated user speed of x5. In my opinion, the marker should be stationary and only the map should move. In my other issue I described that an icon defined in directionArrowMarker seems to have no effect on iOS. This problem still exists - On iOS, the icon defined in the personMarker property is displayed, while on Android, the icon defined in the directionArrowMarker property is displayed. Thank you again!

for `directionArrowMarker`did you test real iphone ? because `directionArrowMarker` also shown when heading != 0 
or you have another use case for it ?

**Comment by tmp78** [comment]
@liodali, this issue is closed, so i will continue in my issue #508 where I also mention about it.
